FORMAT: 1A

# test-spring-mvc

Test spring mvc rest api

## Status for V1 [/v1/status]

A Question object has the following attributes:

+ url

### Test get [GET]

+ Response 200 (application/json)

                {
                    "status": true
                }