FORMAT: 1A

# test-spring-mvc

Test spring mvc rest api with URL versioning

## Status for V1 [/v1/status]

A Question object has the following attributes:

### Status for V1 [GET]

+ Response 200 (application/json;charset=UTF-8)

                {
                    "text": "Hello API V1"
                    "status": true
                }
                
## Status for V2 [/v2/status]
                
### Status for V2 [GET]

+ Response 200 (application/json;charset=UTF-8)

                {
                    "text": "Hello API V2"
                    "status": true
                }